# Laboratory 8 : System of Linear Equations <br>
Coded and Submitted By:<br>
Santos, Franz Nico<br>
201813672<br>
58011

In [68]:
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib inline


The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. The admission was 122 dollars for 8 children and 3 adults in another music concert. How much was the admission for each child and adult?
$$\begin{bmatrix} 3a + 12c\\ 3a + 8c \end{bmatrix}\cdot\begin{bmatrix}a\\c\end{bmatrix} = \begin{bmatrix}162\\122\end{bmatrix} $$


In [82]:
people = np.array([
    [3, 12],
    [3, 8]
])
cost = np.array([
    [162],
    [122]
])
print (people)
print (people.shape)
print (cost)
print (cost.shape)


[[ 3 12]
 [ 3  8]]
(2, 2)
[[162]
 [122]]
(2, 1)


In [83]:
prices = np.linalg.inv(people) @ cost  
print('The cost of admission per adult is: ${:.2f}'.format(float(prices[0])))
print('The cost of admission per child is: ${:.2f}'.format(float(prices[1])))

The cost of admission per adult is: $14.00
The cost of admission per child is: $10.00


In [32]:
people_inv = np.linalg.inv(people)
people_inv

array([[-0.66666667,  1.        ],
       [ 0.25      , -0.25      ]])

In [33]:
r = people_inv @ cost
r

array([[14.],
       [10.]])

In [38]:
Y_1 = people @ r
np.array_equal(Y_1, cost)

True

array([[453.],
       [369.]])

In [39]:
people_sol = np.linalg.solve(people,cost)
people_sol

array([[14.],
       [10.]])

$$\begin{bmatrix} a + c\\ 7a + 4c \end{bmatrix}\cdot\begin{bmatrix}a\\c\end{bmatrix} = \begin{bmatrix}88\\553\end{bmatrix} $$


In [142]:
customers = np.array([
    [1, 1],
    [7, 4]
])
costs = np.array([
    [88],
    [553]
])
print (customers)
print (customers.shape)
print (cost)
print (cost.shape)



[[1 1]
 [7 4]]
(2, 2)
[[ 88]
 [553]]
(2, 1)


In [143]:
prices = np.linalg.inv(customers) @ costs
print('The number of tickets sold for the adult is: {:.2f}'.format(float(prices[0])))
print('The number of tickets sold for the child is: {:.2f}'.format(float(prices[1])))



The number of tickets sold for the adult is: 67.00
The number of tickets sold for the child is: 21.00


In [144]:
customers_inv = np.linalg.inv(customers)
customers_inv

array([[-1.33333333,  0.33333333],
       [ 2.33333333, -0.33333333]])

In [145]:
r = customers_inv @ costs
r

array([[67.],
       [21.]])

In [150]:
customers @ r

array([[ 88.],
       [553.]])

In [123]:
customer_sol = np.linalg.solve(customers,costs)
customer_sol

array([[67.],
       [21.]])